<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="7" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<br><a target="_blank" href="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_01_Create_New_Other_User_01_12_2021_10_24_13.png"><img src="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_01_Create_New_Other_User_01_12_2021_10_24_13.png" height='100' width='150'/> </a></br>]]>
    </line>
    <line>
      <![CDATA[<br><a target="_blank" href="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_02_Create_New_Customer_And_Checked_Created_Succesfully_01_12_2021_10_24_19.png"><img src="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_02_Create_New_Customer_And_Checked_Created_Succesfully_01_12_2021_10_24_19.png" height='100' width='150'/> </a></br>]]>
    </line>
  </reporter-output>
  <suite started-at="2021-12-01T15:23:58Z" name="UploadFile" finished-at="2021-12-01T15:24:56Z" duration-ms="57733">
    <groups>
    </groups>
    <test started-at="2021-12-01T15:23:58Z" name="Run on CHROME" finished-at="2021-12-01T15:24:56Z" duration-ms="57733">
      <class name="com.bankguru.livecodingproject.paymentTestCase">
        <test-method is-config="true" signature="deleteAllFilesInReportNGScreenshot()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:23:59Z" name="deleteAllFilesInReportNGScreenshot" finished-at="2021-12-01T15:23:59Z" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAllFilesInReportNGScreenshot -->
        <test-method is-config="true" signature="beforeClass(java.lang.String, java.lang.String)[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:23:59Z" name="beforeClass" finished-at="2021-12-01T15:24:04Z" duration-ms="5507" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://demo.guru99.com/V4/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="TC_01_Create_New_Other_User()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:04Z" name="TC_01_Create_New_Other_User" finished-at="2021-12-01T15:24:13Z" duration-ms="8649" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [01/01/1989] but found [1989-01-01]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [01/01/1989] but found [1989-01-01]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at commons.BaseTest.checkEquals(BaseTest.java:166)
at commons.BaseTest.verifyEquals(BaseTest.java:178)
at com.bankguru.livecodingproject.paymentTestCase.TC_01_Create_New_Other_User(paymentTestCase.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br><a target="_blank" href="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_01_Create_New_Other_User_01_12_2021_10_24_13.png"><img src="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_01_Create_New_Other_User_01_12_2021_10_24_13.png" height='100' width='150'/> </a></br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC_01_Create_New_Other_User -->
        <test-method signature="TC_02_Create_New_Customer_And_Checked_Created_Succesfully()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:13Z" name="TC_02_Create_New_Customer_And_Checked_Created_Succesfully" finished-at="2021-12-01T15:24:19Z" duration-ms="6437" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [01/01/1989] but found [1989-01-01]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [01/01/1989] but found [1989-01-01]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at commons.BaseTest.checkEquals(BaseTest.java:166)
at commons.BaseTest.verifyEquals(BaseTest.java:178)
at com.bankguru.livecodingproject.paymentTestCase.TC_02_Create_New_Customer_And_Checked_Created_Succesfully(paymentTestCase.java:293)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br><a target="_blank" href="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_02_Create_New_Customer_And_Checked_Created_Succesfully_01_12_2021_10_24_19.png"><img src="file:///C:\Users\quanh\git\Automation-framework/screenshotReportNG/TC_02_Create_New_Customer_And_Checked_Created_Succesfully_01_12_2021_10_24_19.png" height='100' width='150'/> </a></br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC_02_Create_New_Customer_And_Checked_Created_Succesfully -->
        <test-method signature="TC_03_Edit_Customer_Account_And_Check_Edit_Succesfully()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:19Z" name="TC_03_Edit_Customer_Account_And_Check_Edit_Succesfully" finished-at="2021-12-01T15:24:24Z" duration-ms="4510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_Edit_Customer_Account_And_Check_Edit_Succesfully -->
        <test-method signature="TC_04_Add_New_Account()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:24Z" name="TC_04_Add_New_Account" finished-at="2021-12-01T15:24:27Z" duration-ms="2981" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_Add_New_Account -->
        <test-method signature="TC_05_Edit_Account()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:27Z" name="TC_05_Edit_Account" finished-at="2021-12-01T15:24:32Z" duration-ms="4801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_05_Edit_Account -->
        <test-method signature="TC_06_Tranfer_Money_Into_A_Current_Account()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:32Z" name="TC_06_Tranfer_Money_Into_A_Current_Account" finished-at="2021-12-01T15:24:35Z" duration-ms="3875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_06_Tranfer_Money_Into_A_Current_Account -->
        <test-method signature="TC_07_WithDraw_Money_From_Current_Account()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:35Z" name="TC_07_WithDraw_Money_From_Current_Account" finished-at="2021-12-01T15:24:39Z" duration-ms="3805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_07_WithDraw_Money_From_Current_Account -->
        <test-method signature="TC_08_Transfer_The_Money_Into_Another_Account()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:39Z" name="TC_08_Transfer_The_Money_Into_Another_Account" finished-at="2021-12-01T15:24:43Z" duration-ms="3904" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_08_Transfer_The_Money_Into_Another_Account -->
        <test-method signature="TC_09_Check_Current_Account_Balance_Equal_3000()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:43Z" name="TC_09_Check_Current_Account_Balance_Equal_3000" finished-at="2021-12-01T15:24:46Z" duration-ms="3151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_09_Check_Current_Account_Balance_Equal_3000 -->
        <test-method signature="TC_10_Delete_All_Account()[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:46Z" name="TC_10_Delete_All_Account" finished-at="2021-12-01T15:24:56Z" duration-ms="9860" status="FAIL">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Multiple failures (2):
Failure 1 of 2
java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at commons.BaseTest.checkTrue(BaseTest.java:127)
at commons.BaseTest.verifyTrue(BaseTest.java:139)
at com.bankguru.livecodingproject.paymentTestCase.TC_10_Delete_All_Account(paymentTestCase.java:630)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)

Failure 2 of 2
java.lang.AssertionError: expected [Account Deleted Sucessfully] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Multiple failures (2):
Failure 1 of 2
java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at commons.BaseTest.checkTrue(BaseTest.java:127)
at commons.BaseTest.verifyTrue(BaseTest.java:139)
at com.bankguru.livecodingproject.paymentTestCase.TC_10_Delete_All_Account(paymentTestCase.java:630)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)

Failure 2 of 2
java.lang.AssertionError: expected [Account Deleted Sucessfully] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at commons.BaseTest.checkEquals(BaseTest.java:166)
at commons.BaseTest.verifyEquals(BaseTest.java:178)
at com.bankguru.livecodingproject.paymentTestCase.TC_10_Delete_All_Account(paymentTestCase.java:640)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_10_Delete_All_Account -->
        <test-method is-config="true" signature="cleanBrowser(java.lang.String)[pri:0, instance:com.bankguru.livecodingproject.paymentTestCase@45385f75]" started-at="2021-12-01T15:24:56Z" name="cleanBrowser" finished-at="2021-12-01T15:24:56Z" duration-ms="62" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanBrowser -->
      </class> <!-- com.bankguru.livecodingproject.paymentTestCase -->
    </test> <!-- Run on CHROME -->
  </suite> <!-- UploadFile -->
</testng-results>
